---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ssapmcco/apps/ActivosApp
    - /bin/echo "Desplegando aplicación Django en $DEPLOYPATH"

    - /bin/rsync -av --delete \
    --exclude='.git' \
    --exclude='venv' \
    --exclude='__pycache__' \
    --exclude='tmp' \
    --exclude='node_modules' \
    --exclude='.env' \
    --exclude='passenger_wsgi.py' \
    --exclude='.htaccess' \
    ./ $DEPLOYPATH
    
    # 6️⃣ Recolecta archivos estáticos
    - /home/ssapmcco/virtualenv/Activos/3.11/bin/python $DEPLOYPATH/manage.py collectstatic --noinput --clear

    # 7️⃣ Reinicia Passenger (para recargar la app en producción)
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
