---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/ssapmcco/apps/ActivosApp
    - export REPO_PATH=/home/ssapmcco/repositories/Activos

     # 🧹 Limpiar archivos antiguos del destino (sin tocar logs o tmp)
    - /usr/bin/find $DEPLOY_PATH -mindepth 1 -maxdepth 1 ! -name "logs" ! -name "tmp" -exec rm -rf {} \;

    - /bin/rsync -avz --exclude='.git*' --exclude='.cpanel.yml' --exclude='tests/' --exclude='.env' $REPO_PATH/ $DEPLOY_PATH/
