# Generated by Django 5.2.7 on 2025-10-06 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0002_historialmovimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=150, verbose_name='Técnico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('descripcion', models.TextField(verbose_name='Descripción del Mantenimiento')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('estado', models.CharField(choices=[('EP', 'En proceso'), ('FI', 'Finalizado')], default='EP', max_length=2, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='activos.activo', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['activo', '-fecha'], name='mantenimien_activo__2809f4_idx'), models.Index(fields=['estado'], name='mantenimien_estado_0cfa99_idx')],
            },
        ),
    ]
