# Generated by Django 5.2.7 on 2025-10-06 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GE', 'Reporte General de Activos'), ('NE', 'Nota de Entrega')], max_length=2, verbose_name='Tipo de Reporte')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('filtros_aplicados', models.JSONField(blank=True, default=dict, verbose_name='Filtros Aplicados')),
                ('cantidad_activos', models.PositiveIntegerField(verbose_name='Cantidad de Activos')),
                ('archivo_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Archivo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
