# Generated by Django 5.1.6 on 2025-10-05 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('CR', 'Creación'), ('AC', 'Actualización'), ('RE', 'Reasignación'), ('RU', 'Reubicación'), ('CE', 'Cambio de Estado'), ('EL', 'Eliminación')], max_length=2)),
                ('descripcion', models.TextField()),
                ('campo_modificado', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_movimientos', to='activos.activo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_activos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Movimiento',
                'verbose_name_plural': 'Historial de Movimientos',
                'ordering': ['-fecha_movimiento'],
                'indexes': [models.Index(fields=['activo', '-fecha_movimiento'], name='activos_his_activo__b4a8a8_idx'), models.Index(fields=['tipo_movimiento'], name='activos_his_tipo_mo_07e8dc_idx')],
            },
        ),
    ]
